// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "enable": boolean;
      "llmBaseUrl": string;
      "llmModel": string;
      "llmApiKey": string;
      "embeddingBaseUrl": string;
      "embeddingModel": string;
      "enableHybridSearch": boolean;
      "requireEvidence": boolean;
      "localMode": boolean;
      "localBaseUrl": string;
      "localChatModel": string;
      "localEmbeddingModel": string;
      "readerStandalone": boolean;
    };
  }
}
